//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub portal_platform: String,
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::portal_platform::Entity",
        from = "Column::PortalPlatform",
        to = "super::portal_platform::Column::Name",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    PortalPlatform,
    #[sea_orm(has_many = "super::tagged_channel::Entity")]
    TaggedChannel,
}

impl Related<super::portal_platform::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PortalPlatform.def()
    }
}

impl Related<super::tagged_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaggedChannel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
