//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

pub mod prelude;

pub mod channel;
pub mod message;
pub mod portal_platform;
pub mod rule;
pub mod source_platform;
pub mod tag;
pub mod tagged_channel;
pub mod tagged_message;
pub mod tagged_rule;
pub mod tagged_user;
pub mod users;
