//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

pub use super::channel::Entity as Channel;
pub use super::message::Entity as Message;
pub use super::portal_platform::Entity as PortalPlatform;
pub use super::rule::Entity as Rule;
pub use super::source_platform::Entity as SourcePlatform;
pub use super::tag::Entity as Tag;
pub use super::tagged_channel::Entity as TaggedChannel;
pub use super::tagged_message::Entity as TaggedMessage;
pub use super::tagged_rule::Entity as TaggedRule;
pub use super::tagged_user::Entity as TaggedUser;
pub use super::users::Entity as Users;
